### ISSUE TITLE
Some errors when I run ''npm install''!

### ISSUE THREAD

**Issue by StevenWash** [ikismail/Angular4-ShoppingCart#1]
Hi,
When I clone this project into my local workspace, I run 'npm install', but it happened like this:
![image](https://user-images.githubusercontent.com/18731292/39095306-f2bf535e-4670-11e8-8cfa-ebb66b80b369.png)
So,what can I do ?Thank you very much!

**Comment by ikismail** [comment]
Hello Steven,
  Try to use yarn package manager. I used Yarn as my package manager.

If still face the issue after yarn. Then let me know will try to fix this.

Thanks,
Mohammed Ismail,

**Comment by StevenWash** [comment]
Hello ikismail,
   I am happy to tell you I have run this program successfully. And I re-install the node and npm to the specify version in your package.json , and to run npm install again ,then it work fine!

Thank you very much!

**Comment by ikismail** [comment]
Great Steven, 

Sent from Mail for Windows 10

**Comment by ikismail** [comment]
and closing this issue.

**Comment by ikismail** [comment]
and closing this issue
