### ISSUE TITLE
Cannot find module 'moment'when app served 

### ISSUE THREAD

**Issue by SiddhantPotghante** [ikismail/Angular4-ShoppingCart#2]
ERROR in C:/~~/src/app/user/shared/user.service.ts (9,25): Cannot find module 'moment'.

**Comment by ikismail** [comment]
Fixed this issue [#714617c]( https://github.com/ikismail/Angular4-ShoppingCart/commit/714617c0f8fd78172b33f6c2c0df01944f0b5ecf ) just pull and run the npm install or yarn install again. @SiddhantPotghante closing this for now.
